<?php

use Drupal\drupal_ad\Model\Utility;
/**
 * @file
 * Module file for Drupal ldap Module.
 */

function drupal_ad_preprocess_node__page(array &$variables): void {
  $variables['#attached']['library'][] = 'core/jquery';
  $variables['#attached']['library'][] = 'core/fontawesome';
  $variables['#attached']['library'][] = 'core/drupal.dialog.ajax';
  $variables['#attached']['library'][] = 'field_group/formatter.horizontal_tabs';
}

function drupal_ad_form_alter(&$form, &$form_state, $form_id) {
  $isAdmin = Drupal::service('router.admin_context')->isAdminRoute();
  $moduleLink = Drupal::request()->getRequestUri();
  if ($isAdmin && strpos($moduleLink, 'drupal_ad') !== FALSE) {
    Utility::add_message(t('<b> For any queries or support reach out on email at <a target="_blank" href="mailto:simonsiva13@@gmail.com">simonsiva13@@gmail.com</a> </b>.'), 'warning');
  }
  if (!\Drupal::currentUser()->isAuthenticated()) {
    $form_ids = [
      'user_login_block',
      'user_login',
      'user_login_form',
      'user-login-form',
    ];
    $enableLdapLogin = Drupal::config('drupal_ad.settings')
      ->get('drupal_ldap_enable_ldap');
    if (in_array($form_id, $form_ids) && $enableLdapLogin) {
      array_unshift($form['#validate'], 'drupal_ad_authenticate_submit');
    }
  }
}


